package com.solproe.business.dto;

public enum AlertThreshold {
    RED_FIRE_FOREST_THRESHOLD("ACTIVAR EN PREVENTIVO EL PMU Y ALISTAMIENTO DE BRIGADAS DE EMERGENCIAS " +
            "(EQUIPOS LISTOS PARA REACCIÓN INMEDIATA)"),
    ORANGE_FIRE_FOREST_THRESHOLD("ALISTAMIENTO DE BRIGADAS DE EMERGENCIAS"),
    RED_MASS_MOVEMENT_THRESHOLD("ACTIVAR EN PREVENTIVO EL PMU Y ALISTAMIENTO DE BRIGADAS DE EMERGENCIAS" +
            " (EQUIPOS LISTOS PARA REACCIÓN INMEDIATA)"),
    ORANGE_MASS_MOVEMENT_THRESHOLD("ALISTAMIENTO DE BRIGADAS DE EMERGENCIAS"),
    YELLOW_MASS_MOVEMENT_THRESHOLD("PREPARACIÓN PARA LA RESPUESTA, ALISTAMIENTO DE RECURSOS, " +
            "SUMINISTROS Y SERVICIOS E IDENTIFICACIÓN DE DE LAS RUTAS DE INGRESO Y EGRESO."),
    RED_WIND_SPEED_THRESHOLD("ACTIVAR EN PREVENTIVO EL PMU Y ALISTAMIENTO DE BRIGADAS DE EMERGENCIAS" +
            " (EQUIPOS LISTOS PARA REACCIÓN INMEDIATA)"),
    ORANGE_WIND_SPEED_THRESHOLD("ALISTAMIENTO DE BRIGADAS DE EMERGENCIAS");

    private final String mensaje;

    AlertThreshold(String mensaje) {
        this.mensaje = mensaje;
    }

    public String getMessage() {
        return this.mensaje;
    }
}
